from time import strftime,gmtime


def get_excel_data(i, time, sheet, request):
    print("----------")
    print(sheet.cell_value(i,2))
    return {
                    'timestamp': time,
                    'username': request.session['username'],
                    'Sector':sheet.cell_value(i,0),
                    'Cluster':sheet.cell_value(i,1),
                    'Sub_Cluster':sheet.cell_value(i,2),
                    'Congested':sheet.cell_value(i,3),
                    'Leakage':sheet.cell_value(i,4),
                    'DCR':sheet.cell_value(i,5),
                    'AFR':sheet.cell_value(i,6),
                    'Misc':sheet.cell_value(i,7),
                    'Analysis':sheet.cell_value(i,8),
                    'Last_updated':sheet.cell_value(i,9),
                    'Comments':sheet.cell_value(i,10),

                    'Optimization_Completed':sheet.cell_value(i,11),
                    'Status':sheet.cell_value(i,12),
                    'Perm_Solution':sheet.cell_value(i,13),
                    'Development_Priority':sheet.cell_value(i,14),
                    'Cell_Split':sheet.cell_value(i,15),
                    'Coverage Strategy':sheet.cell_value(i,16),
                    'DART':sheet.cell_value(i,17),
                    'Hardening_National':sheet.cell_value(i,18),
                    'L1900_Capacity':sheet.cell_value(i,19),
                    'L2100_Capacity':sheet.cell_value(i,20),
                    'L700':sheet.cell_value(i,21),
                    'Market_Infill':sheet.cell_value(i,22),
                    'Modernization':sheet.cell_value(i,23),
                    'New_Build_Infill':sheet.cell_value(i,24),
                    'Replacement':sheet.cell_value(i,25),
                    'ROB':sheet.cell_value(i,26),
                    'Rural America':sheet.cell_value(i,27),
                    'Sector_Add':sheet.cell_value(i,28),
                    'Small_Cell_Strategy':sheet.cell_value(i,29),
                    'T_Mobile_Store':sheet.cell_value(i,30),
                    'Venue ACS':sheet.cell_value(i,31),
                    'Cell_Split_ID':sheet.cell_value(i,32),
            }

def get_post_data(request):
    return {
        'username': request.session['username'],
        'timestamp': strftime("%a, %d %b %Y %H:%M:%S", gmtime()),
        'Sector': request.POST['0'],
        'Cluster': request.POST['1'],
        'Sub_Cluster': request.POST['2'],
        'Congested':request.POST['3'],
        'Leakage':request.POST['4'],
        'DCR': request.POST['5'],
        'AFR': request.POST['6'],
        'Misc': request.POST['7'],
        'Analysis': request.POST['8'],
        'Last_updated': request.POST['9'],
        'Comments': request.POST['10'],
        'Optimization_Completed': request.POST['11'],
        'Status': request.POST['12'],
        'Perm_Solution': request.POST['13'],
        'Development_Priority': request.POST['14'],
        'Cell_Split': request.POST['15'],
        'Coverage_Strategy': request.POST['16'],
        'DART': request.POST['17'],
        'Hardening_National': request.POST['18'],
        'L1900_Capacity': request.POST['19'],
        'L2100_Capacity': request.POST['20'],
        'L700': request.POST['21'],
        'Market_Infill': request.POST['22'],
        'Modernization': request.POST['23'],
        'New_Build_Infill': request.POST['24'],
        'Replacement': request.POST['25'],
        'ROB': request.POST['26'],
        'Rural_America': request.POST['27'],
        'Sector_Add': request.POST['28'],
        'Small_Cell_Strategy': request.POST['29'],
        'T_Mobile_Store': request.POST['30'],
        'Venue_ACS': request.POST['31'],
        'Cell_Split_ID': request.POST['32'],
        }
