# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('timestamp', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
