# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0003_auto_20170406_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excelfiles',
            old_name='file',
            new_name='filee',
        ),
        migrations.AddField(
            model_name='excelfiles',
            name='file_name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='excelfiles',
            name='username',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
