# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0004_auto_20170406_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfiles',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='excelfiles',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
