# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0005_auto_20170406_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfiles',
            name='sector',
            field=models.CharField(default='sector', max_length=50),
        ),
        migrations.AddField(
            model_name='excelfiles',
            name='timestamp',
            field=models.CharField(default='time', max_length=50),
        ),
        migrations.AlterField(
            model_name='excelfiles',
            name='username',
            field=models.CharField(default='username', max_length=50),
        ),
    ]
